FROM node:20-alpine
WORKDIR /app
COPY medmcq-eb-standalone-v3.zip ./
RUN apk add --no-cache unzip && \
    unzip medmcq-eb-standalone-v3.zip -d . && \
    rm medmcq-eb-standalone-v3.zip

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
EXPOSE 3000

CMD ["node", "server.js"]
